"""Enterprise skill taxonomy.

Each entry is ``(canonical name, category, market weight, aliases)``.

* **weight** expresses relative market importance and drives the weighted ATS
  score. ``1.0`` is the baseline, ``0.7`` marks commodity tools and ``1.4``
  marks high-demand specialisations.
* **aliases** capture the spellings recruiters and candidates actually use
  (``"js"``, ``"k8s"``, ``"postgres"``), which is what makes synonym matching
  work.

The catalog is intentionally data-only: the detection engine in
:mod:`resume_analyzer.skills.registry` compiles it into regular expressions
once per process, so adding a skill here needs no code changes.

Guidelines when extending:

* Canonical names use the vendor's own casing (``"PostgreSQL"``, ``"Node.js"``).
* Never add an alias shorter than three characters unless it is unambiguous in
  a resume context (``"AWS"`` is safe, ``"AI"`` as an alias of anything is not).
* Aliases must be lowercase; matching is case-insensitive.
"""

from __future__ import annotations

from typing import Final

from resume_analyzer.domain.models import SkillCategory

SkillSpec = tuple[str, SkillCategory, float, tuple[str, ...]]

C = SkillCategory

# ---------------------------------------------------------------------------
# Programming languages
# ---------------------------------------------------------------------------

_PROGRAMMING: Final[tuple[SkillSpec, ...]] = (
    ("Python", C.PROGRAMMING_LANGUAGE, 1.3, ("python3", "python 3", "py")),
    ("JavaScript", C.PROGRAMMING_LANGUAGE, 1.3, ("js", "ecmascript", "es6", "es2015")),
    ("TypeScript", C.PROGRAMMING_LANGUAGE, 1.3, ("ts",)),
    ("Java", C.PROGRAMMING_LANGUAGE, 1.2, ("java se", "java ee", "j2ee", "jdk")),
    ("C++", C.PROGRAMMING_LANGUAGE, 1.1, ("cpp", "c plus plus", "c++11", "c++17")),
    ("C#", C.PROGRAMMING_LANGUAGE, 1.1, ("csharp", "c sharp")),
    ("C", C.PROGRAMMING_LANGUAGE, 1.0, ("ansi c",)),
    ("Go", C.PROGRAMMING_LANGUAGE, 1.2, ("golang",)),
    ("Rust", C.PROGRAMMING_LANGUAGE, 1.2, ()),
    ("Ruby", C.PROGRAMMING_LANGUAGE, 1.0, ()),
    ("PHP", C.PROGRAMMING_LANGUAGE, 0.9, ()),
    ("Swift", C.PROGRAMMING_LANGUAGE, 1.1, ("swiftui",)),
    ("Kotlin", C.PROGRAMMING_LANGUAGE, 1.1, ()),
    ("Objective-C", C.PROGRAMMING_LANGUAGE, 0.8, ("objective c", "objc")),
    ("Scala", C.PROGRAMMING_LANGUAGE, 1.1, ()),
    ("R", C.PROGRAMMING_LANGUAGE, 1.0, ("r language", "r programming")),
    ("MATLAB", C.PROGRAMMING_LANGUAGE, 0.9, ()),
    ("Perl", C.PROGRAMMING_LANGUAGE, 0.7, ()),
    ("Lua", C.PROGRAMMING_LANGUAGE, 0.8, ()),
    ("Haskell", C.PROGRAMMING_LANGUAGE, 0.9, ()),
    ("Elixir", C.PROGRAMMING_LANGUAGE, 1.0, ()),
    ("Erlang", C.PROGRAMMING_LANGUAGE, 0.9, ()),
    ("Clojure", C.PROGRAMMING_LANGUAGE, 0.9, ()),
    ("F#", C.PROGRAMMING_LANGUAGE, 0.8, ("fsharp",)),
    ("Dart", C.PROGRAMMING_LANGUAGE, 1.0, ()),
    ("Groovy", C.PROGRAMMING_LANGUAGE, 0.8, ()),
    ("Julia", C.PROGRAMMING_LANGUAGE, 0.9, ()),
    ("Visual Basic", C.PROGRAMMING_LANGUAGE, 0.6, ("vb.net", "vba")),
    ("Assembly", C.PROGRAMMING_LANGUAGE, 0.8, ("assembler", "x86 assembly")),
    ("COBOL", C.PROGRAMMING_LANGUAGE, 0.7, ()),
    ("Fortran", C.PROGRAMMING_LANGUAGE, 0.6, ()),
    ("Solidity", C.PROGRAMMING_LANGUAGE, 1.1, ()),
    ("SQL", C.PROGRAMMING_LANGUAGE, 1.3, ("structured query language", "t-sql", "pl/sql")),
    ("Bash", C.PROGRAMMING_LANGUAGE, 1.0, ("shell scripting", "bash scripting", "zsh")),
    ("PowerShell", C.PROGRAMMING_LANGUAGE, 0.9, ("power shell",)),
    ("Scheme", C.PROGRAMMING_LANGUAGE, 0.6, ("lisp", "common lisp")),
)

# ---------------------------------------------------------------------------
# Frontend
# ---------------------------------------------------------------------------

_FRONTEND: Final[tuple[SkillSpec, ...]] = (
    ("React", C.FRONTEND, 1.3, ("react.js", "reactjs")),
    ("Next.js", C.FRONTEND, 1.2, ("nextjs", "next js")),
    ("Angular", C.FRONTEND, 1.1, ("angularjs", "angular 2")),
    ("Vue.js", C.FRONTEND, 1.1, ("vue", "vuejs")),
    ("Nuxt.js", C.FRONTEND, 1.0, ("nuxt", "nuxtjs")),
    ("Svelte", C.FRONTEND, 1.1, ("sveltekit",)),
    ("SolidJS", C.FRONTEND, 0.9, ("solid.js",)),
    ("Ember.js", C.FRONTEND, 0.7, ("emberjs",)),
    ("Backbone.js", C.FRONTEND, 0.6, ("backbonejs",)),
    ("jQuery", C.FRONTEND, 0.7, ()),
    ("HTML", C.FRONTEND, 0.8, ("html5",)),
    ("CSS", C.FRONTEND, 0.8, ("css3",)),
    ("Sass", C.FRONTEND, 0.9, ("scss",)),
    ("Less", C.FRONTEND, 0.7, ()),
    ("Tailwind CSS", C.FRONTEND, 1.0, ("tailwind", "tailwindcss")),
    ("Bootstrap", C.FRONTEND, 0.8, ()),
    ("Material UI", C.FRONTEND, 0.9, ("mui", "material-ui")),
    ("Chakra UI", C.FRONTEND, 0.8, ()),
    ("Redux", C.FRONTEND, 1.0, ("redux toolkit", "redux-saga")),
    ("MobX", C.FRONTEND, 0.8, ()),
    ("Zustand", C.FRONTEND, 0.9, ()),
    ("React Query", C.FRONTEND, 1.0, ("tanstack query",)),
    ("Webpack", C.FRONTEND, 0.9, ()),
    ("Vite", C.FRONTEND, 1.0, ()),
    ("Babel", C.FRONTEND, 0.8, ()),
    ("ESLint", C.FRONTEND, 0.8, ()),
    ("Storybook", C.FRONTEND, 0.9, ()),
    ("Web Components", C.FRONTEND, 0.8, ()),
    ("Responsive Design", C.FRONTEND, 0.9, ("mobile-first design", "responsive web design")),
    ("Web Accessibility", C.FRONTEND, 1.0, ("wcag", "a11y", "accessibility standards")),
    ("Progressive Web Apps", C.FRONTEND, 0.9, ("pwa",)),
    ("Three.js", C.FRONTEND, 0.9, ("threejs",)),
    ("D3.js", C.FRONTEND, 1.0, ("d3js",)),
    ("Astro", C.FRONTEND, 0.9, ()),
    ("Remix", C.FRONTEND, 0.9, ()),
    ("Streamlit", C.FRONTEND, 1.0, ()),
)

# ---------------------------------------------------------------------------
# Backend, frameworks, APIs
# ---------------------------------------------------------------------------

_BACKEND: Final[tuple[SkillSpec, ...]] = (
    ("Node.js", C.BACKEND, 1.2, ("nodejs", "node")),
    ("Express.js", C.BACKEND, 1.0, ("express", "expressjs")),
    ("NestJS", C.BACKEND, 1.1, ("nest.js",)),
    ("Django", C.BACKEND, 1.2, ("django rest framework", "drf")),
    ("Flask", C.BACKEND, 1.1, ()),
    ("FastAPI", C.BACKEND, 1.2, ("fast api",)),
    ("Tornado", C.BACKEND, 0.7, ()),
    ("Spring Boot", C.BACKEND, 1.2, ("springboot", "spring framework", "spring")),
    ("Hibernate", C.BACKEND, 0.9, ("jpa",)),
    ("Micronaut", C.BACKEND, 0.8, ()),
    ("Quarkus", C.BACKEND, 0.9, ()),
    (".NET", C.BACKEND, 1.1, ("dotnet", ".net core", "asp.net", "asp.net core")),
    ("Ruby on Rails", C.BACKEND, 1.0, ("rails", "ror")),
    ("Laravel", C.BACKEND, 0.9, ()),
    ("Symfony", C.BACKEND, 0.8, ()),
    ("CodeIgniter", C.BACKEND, 0.6, ()),
    ("Gin", C.BACKEND, 0.9, ("gin-gonic",)),
    ("Fiber", C.BACKEND, 0.8, ()),
    ("Actix", C.BACKEND, 0.9, ("actix-web",)),
    ("Phoenix", C.BACKEND, 0.9, ()),
    ("REST API", C.BACKEND, 1.2, ("rest", "restful", "restful api", "rest apis", "restful services")),
    ("GraphQL", C.BACKEND, 1.1, ("apollo graphql",)),
    ("gRPC", C.BACKEND, 1.1, ("grpc-web",)),
    ("WebSockets", C.BACKEND, 1.0, ("websocket", "socket.io")),
    ("Microservices", C.BACKEND, 1.2, ("microservice architecture", "microservices architecture")),
    ("Serverless", C.BACKEND, 1.1, ("serverless architecture", "faas")),
    ("Event-Driven Architecture", C.BACKEND, 1.1, ("event driven", "event sourcing")),
    ("Domain-Driven Design", C.BACKEND, 1.1, ("ddd", "domain driven design")),
    ("API Gateway", C.BACKEND, 1.0, ()),
    ("OAuth", C.BACKEND, 1.0, ("oauth2", "oauth 2.0")),
    ("JWT", C.BACKEND, 0.9, ("json web token",)),
    ("OpenAPI", C.BACKEND, 0.9, ("swagger",)),
    ("Celery", C.BACKEND, 0.9, ()),
    ("RabbitMQ", C.BACKEND, 1.0, ()),
    ("Apache Kafka", C.BACKEND, 1.3, ("kafka",)),
    ("Apache Pulsar", C.BACKEND, 0.9, ("pulsar",)),
    ("NATS", C.BACKEND, 0.8, ()),
    ("ActiveMQ", C.BACKEND, 0.7, ()),
    ("Nginx", C.BACKEND, 1.0, ()),
    ("Apache HTTP Server", C.BACKEND, 0.8, ("apache2", "httpd")),
    ("Caching Strategies", C.BACKEND, 1.0, ("caching", "cache invalidation")),
    ("Load Balancing", C.BACKEND, 1.0, ("load balancer",)),
    ("Rate Limiting", C.BACKEND, 0.9, ()),
    ("System Design", C.BACKEND, 1.3, ("distributed systems", "scalable systems")),
    ("Multithreading", C.BACKEND, 1.0, ("concurrency", "parallel programming", "async programming")),
)

# ---------------------------------------------------------------------------
# Databases and storage
# ---------------------------------------------------------------------------

_DATABASES: Final[tuple[SkillSpec, ...]] = (
    ("PostgreSQL", C.DATABASE, 1.2, ("postgres", "psql")),
    ("MySQL", C.DATABASE, 1.1, ("mariadb",)),
    ("SQLite", C.DATABASE, 0.9, ()),
    ("Microsoft SQL Server", C.DATABASE, 1.0, ("sql server", "mssql")),
    ("Oracle Database", C.DATABASE, 1.0, ("oracle db", "oracle sql")),
    ("MongoDB", C.DATABASE, 1.1, ("mongo",)),
    ("Redis", C.DATABASE, 1.1, ()),
    ("Cassandra", C.DATABASE, 1.1, ("apache cassandra",)),
    ("DynamoDB", C.DATABASE, 1.1, ("amazon dynamodb",)),
    ("Elasticsearch", C.DATABASE, 1.1, ("elastic search", "elk stack", "opensearch")),
    ("Neo4j", C.DATABASE, 1.0, ("graph database",)),
    ("CouchDB", C.DATABASE, 0.7, ()),
    ("Firebase", C.DATABASE, 1.0, ("firestore", "realtime database")),
    ("Supabase", C.DATABASE, 1.0, ()),
    ("CockroachDB", C.DATABASE, 0.9, ()),
    ("InfluxDB", C.DATABASE, 0.9, ("time series database",)),
    ("ClickHouse", C.DATABASE, 1.1, ()),
    ("Snowflake", C.DATABASE, 1.3, ()),
    ("Amazon Redshift", C.DATABASE, 1.2, ("redshift",)),
    ("Google BigQuery", C.DATABASE, 1.2, ("bigquery",)),
    ("Databricks", C.DATABASE, 1.3, ()),
    ("Pinecone", C.DATABASE, 1.2, ("vector database", "vector db")),
    ("Weaviate", C.DATABASE, 1.1, ()),
    ("Chroma", C.DATABASE, 1.0, ("chromadb",)),
    ("Milvus", C.DATABASE, 1.0, ()),
    ("Database Design", C.DATABASE, 1.1, ("schema design", "data modeling", "data modelling")),
    ("Query Optimization", C.DATABASE, 1.1, ("query tuning", "sql optimization", "indexing")),
    ("Database Administration", C.DATABASE, 1.0, ("dba", "database admin")),
    ("Database Replication", C.DATABASE, 1.0, ("sharding", "partitioning")),
    ("ORM", C.DATABASE, 0.9, ("sqlalchemy", "prisma", "typeorm", "sequelize")),
)

# ---------------------------------------------------------------------------
# Cloud platforms and services
# ---------------------------------------------------------------------------

_CLOUD: Final[tuple[SkillSpec, ...]] = (
    ("AWS", C.CLOUD, 1.4, ("amazon web services",)),
    ("Microsoft Azure", C.CLOUD, 1.3, ("azure",)),
    ("Google Cloud Platform", C.CLOUD, 1.3, ("gcp", "google cloud")),
    ("DigitalOcean", C.CLOUD, 0.9, ("digital ocean",)),
    ("Heroku", C.CLOUD, 0.8, ()),
    ("Vercel", C.CLOUD, 1.0, ()),
    ("Netlify", C.CLOUD, 0.9, ()),
    ("Cloudflare", C.CLOUD, 1.1, ("cloudflare workers",)),
    ("Amazon EC2", C.CLOUD, 1.1, ("ec2",)),
    ("Amazon S3", C.CLOUD, 1.1, ("s3",)),
    ("AWS Lambda", C.CLOUD, 1.2, ("lambda functions",)),
    ("Amazon RDS", C.CLOUD, 1.1, ("rds",)),
    ("Amazon EKS", C.CLOUD, 1.2, ("eks",)),
    ("Amazon ECS", C.CLOUD, 1.1, ("ecs", "fargate")),
    ("Amazon CloudFront", C.CLOUD, 1.0, ("cloudfront", "cdn")),
    ("AWS CloudFormation", C.CLOUD, 1.1, ("cloudformation",)),
    ("Azure DevOps", C.CLOUD, 1.1, ("azure pipelines",)),
    ("Azure Functions", C.CLOUD, 1.1, ()),
    ("Azure Kubernetes Service", C.CLOUD, 1.2, ("aks",)),
    ("Google Kubernetes Engine", C.CLOUD, 1.2, ("gke",)),
    ("Google Cloud Functions", C.CLOUD, 1.0, ()),
    ("Cloud Architecture", C.CLOUD, 1.3, ("cloud design", "cloud migration")),
    ("Cloud Security", C.CLOUD, 1.3, ("cloud security posture",)),
    ("Cost Optimization", C.CLOUD, 1.1, ("finops", "cloud cost optimization")),
    ("Multi-Cloud", C.CLOUD, 1.1, ("hybrid cloud",)),
)

# ---------------------------------------------------------------------------
# DevOps, containerisation, IaC, observability
# ---------------------------------------------------------------------------

_DEVOPS: Final[tuple[SkillSpec, ...]] = (
    ("Docker", C.CONTAINERIZATION, 1.3, ("dockerize", "containerization", "containerisation")),
    ("Kubernetes", C.CONTAINERIZATION, 1.4, ("k8s", "kubectl")),
    ("Helm", C.CONTAINERIZATION, 1.1, ("helm charts",)),
    ("Docker Compose", C.CONTAINERIZATION, 1.0, ("docker-compose",)),
    ("Podman", C.CONTAINERIZATION, 0.8, ()),
    ("OpenShift", C.CONTAINERIZATION, 1.0, ("red hat openshift",)),
    ("Istio", C.CONTAINERIZATION, 1.1, ("service mesh", "linkerd")),
    ("Terraform", C.DEVOPS, 1.3, ("hashicorp terraform",)),
    ("Pulumi", C.DEVOPS, 1.0, ()),
    ("Ansible", C.DEVOPS, 1.1, ()),
    ("Puppet", C.DEVOPS, 0.8, ()),
    ("Chef", C.DEVOPS, 0.7, ()),
    ("Vagrant", C.DEVOPS, 0.7, ()),
    ("Infrastructure as Code", C.DEVOPS, 1.2, ("iac",)),
    ("Jenkins", C.DEVOPS, 1.1, ()),
    ("CI/CD", C.DEVOPS, 1.2, ("cicd", "continuous integration", "continuous delivery", "continuous deployment")),
    ("GitHub Actions", C.DEVOPS, 1.1, ("gh actions",)),
    ("GitLab CI", C.DEVOPS, 1.0, ("gitlab ci/cd",)),
    ("CircleCI", C.DEVOPS, 0.9, ("circle ci",)),
    ("Travis CI", C.DEVOPS, 0.7, ()),
    ("TeamCity", C.DEVOPS, 0.7, ()),
    ("Bamboo", C.DEVOPS, 0.6, ()),
    ("ArgoCD", C.DEVOPS, 1.2, ("argo cd", "gitops")),
    ("Flux", C.DEVOPS, 1.0, ("fluxcd",)),
    ("Spinnaker", C.DEVOPS, 0.9, ()),
    ("Prometheus", C.DEVOPS, 1.2, ()),
    ("Grafana", C.DEVOPS, 1.1, ()),
    ("Datadog", C.DEVOPS, 1.2, ()),
    ("New Relic", C.DEVOPS, 1.0, ("newrelic",)),
    ("Splunk", C.DEVOPS, 1.1, ()),
    ("Sentry", C.DEVOPS, 0.9, ()),
    ("OpenTelemetry", C.DEVOPS, 1.1, ("otel",)),
    ("Jaeger", C.DEVOPS, 0.9, ("distributed tracing",)),
    ("PagerDuty", C.DEVOPS, 0.8, ()),
    ("Site Reliability Engineering", C.DEVOPS, 1.3, ("sre", "slo", "sla", "error budget")),
    ("Observability", C.DEVOPS, 1.2, ("monitoring", "alerting", "log aggregation")),
    ("Incident Management", C.DEVOPS, 1.0, ("on-call", "incident response", "postmortem")),
    ("Blue-Green Deployment", C.DEVOPS, 1.0, ("canary deployment", "canary release")),
    ("Capacity Planning", C.DEVOPS, 1.0, ("autoscaling", "auto-scaling")),
    ("HashiCorp Vault", C.DEVOPS, 1.1, ("vault", "secrets management")),
    ("Consul", C.DEVOPS, 0.9, ("service discovery",)),
)

# ---------------------------------------------------------------------------
# AI, machine learning, deep learning, NLP
# ---------------------------------------------------------------------------

_AI_ML: Final[tuple[SkillSpec, ...]] = (
    ("Machine Learning", C.MACHINE_LEARNING, 1.4, ("ml", "machine-learning")),
    ("Deep Learning", C.DEEP_LEARNING, 1.4, ("dl", "neural networks", "neural network")),
    ("Artificial Intelligence", C.AI, 1.3, ("ai",)),
    ("Natural Language Processing", C.NLP, 1.3, ("nlp",)),
    ("Computer Vision", C.AI, 1.3, ("cv", "image recognition", "object detection")),
    ("Reinforcement Learning", C.MACHINE_LEARNING, 1.2, ("rl", "q-learning")),
    ("Supervised Learning", C.MACHINE_LEARNING, 1.0, ("classification", "regression analysis")),
    ("Unsupervised Learning", C.MACHINE_LEARNING, 1.0, ("clustering", "k-means")),
    ("Feature Engineering", C.MACHINE_LEARNING, 1.2, ("feature selection", "feature extraction")),
    ("Model Deployment", C.MACHINE_LEARNING, 1.3, ("model serving", "model inference")),
    ("MLOps", C.MACHINE_LEARNING, 1.4, ("ml ops", "machine learning operations")),
    ("Hyperparameter Tuning", C.MACHINE_LEARNING, 1.1, ("hyperparameter optimization", "grid search")),
    ("Model Evaluation", C.MACHINE_LEARNING, 1.1, ("cross-validation", "cross validation", "a/b testing")),
    ("TensorFlow", C.DEEP_LEARNING, 1.2, ("tensor flow",)),
    ("Keras", C.DEEP_LEARNING, 1.1, ()),
    ("PyTorch", C.DEEP_LEARNING, 1.3, ("torch", "pytorch lightning")),
    ("JAX", C.DEEP_LEARNING, 1.1, ()),
    ("scikit-learn", C.MACHINE_LEARNING, 1.2, ("sklearn", "scikit learn")),
    ("XGBoost", C.MACHINE_LEARNING, 1.2, ("xg boost",)),
    ("LightGBM", C.MACHINE_LEARNING, 1.1, ("light gbm",)),
    ("CatBoost", C.MACHINE_LEARNING, 1.0, ()),
    ("Hugging Face", C.NLP, 1.3, ("huggingface", "transformers library")),
    ("spaCy", C.NLP, 1.1, ()),
    ("NLTK", C.NLP, 0.9, ()),
    ("Gensim", C.NLP, 0.9, ()),
    ("OpenCV", C.AI, 1.1, ("cv2",)),
    ("YOLO", C.AI, 1.1, ("yolov5", "yolov8")),
    ("Transformers", C.NLP, 1.3, ("bert", "gpt", "roberta", "t5")),
    ("Large Language Models", C.AI, 1.4, ("llm", "llms", "foundation models")),
    ("Prompt Engineering", C.AI, 1.3, ("prompt design", "few-shot prompting")),
    ("RAG", C.AI, 1.4, ("retrieval augmented generation", "retrieval-augmented generation")),
    ("LangChain", C.AI, 1.3, ("lang chain",)),
    ("LlamaIndex", C.AI, 1.2, ("llama index",)),
    ("Fine-Tuning", C.AI, 1.3, ("fine tuning", "lora", "peft", "instruction tuning")),
    ("Embeddings", C.AI, 1.2, ("word embeddings", "sentence embeddings", "word2vec")),
    ("OpenAI API", C.AI, 1.3, ("gpt-4", "chatgpt api", "openai")),
    ("Generative AI", C.AI, 1.4, ("genai", "gen ai", "generative models")),
    ("Diffusion Models", C.AI, 1.2, ("stable diffusion",)),
    ("Speech Recognition", C.AI, 1.1, ("asr", "speech-to-text", "whisper")),
    ("Recommender Systems", C.MACHINE_LEARNING, 1.2, ("recommendation engine", "collaborative filtering")),
    ("Time Series Forecasting", C.MACHINE_LEARNING, 1.1, ("time series analysis", "arima", "prophet")),
    ("Anomaly Detection", C.MACHINE_LEARNING, 1.1, ("outlier detection", "fraud detection")),
    ("MLflow", C.MACHINE_LEARNING, 1.2, ("ml flow",)),
    ("Weights & Biases", C.MACHINE_LEARNING, 1.1, ("wandb", "weights and biases")),
    ("Kubeflow", C.MACHINE_LEARNING, 1.1, ()),
    ("Vertex AI", C.MACHINE_LEARNING, 1.1, ("google vertex ai",)),
    ("Amazon SageMaker", C.MACHINE_LEARNING, 1.2, ("sagemaker",)),
    ("Responsible AI", C.AI, 1.1, ("ai ethics", "model fairness", "explainable ai", "xai")),
    ("Vector Search", C.AI, 1.2, ("semantic search", "similarity search")),
)

# ---------------------------------------------------------------------------
# Data engineering, data science, analytics
# ---------------------------------------------------------------------------

_DATA: Final[tuple[SkillSpec, ...]] = (
    ("Pandas", C.DATA_SCIENCE, 1.1, ()),
    ("NumPy", C.DATA_SCIENCE, 1.0, ("numpy arrays",)),
    ("SciPy", C.DATA_SCIENCE, 0.9, ()),
    ("Polars", C.DATA_SCIENCE, 1.1, ()),
    ("Matplotlib", C.DATA_SCIENCE, 0.9, ()),
    ("Seaborn", C.DATA_SCIENCE, 0.9, ()),
    ("Plotly", C.DATA_SCIENCE, 1.0, ("plotly dash", "dash")),
    ("Jupyter", C.DATA_SCIENCE, 0.9, ("jupyter notebook", "jupyterlab")),
    ("Statistics", C.DATA_SCIENCE, 1.1, ("statistical analysis", "hypothesis testing")),
    ("Data Analysis", C.DATA_SCIENCE, 1.1, ("exploratory data analysis", "eda")),
    ("Data Visualization", C.DATA_SCIENCE, 1.1, ("data visualisation", "dashboarding")),
    ("Business Intelligence", C.DATA_SCIENCE, 1.1, ("bi", "bi reporting")),
    ("Power BI", C.DATA_SCIENCE, 1.0, ("powerbi", "power-bi", "dax")),
    ("Tableau", C.DATA_SCIENCE, 1.0, ()),
    ("Looker", C.DATA_SCIENCE, 1.0, ("looker studio",)),
    ("Metabase", C.DATA_SCIENCE, 0.8, ()),
    ("Qlik", C.DATA_SCIENCE, 0.8, ("qlikview", "qlik sense")),
    ("Google Analytics", C.DATA_SCIENCE, 0.8, ("ga4",)),
    ("Apache Spark", C.DATA_ENGINEERING, 1.3, ("spark", "pyspark", "spark sql")),
    ("Apache Hadoop", C.DATA_ENGINEERING, 0.9, ("hadoop", "hdfs", "mapreduce")),
    ("Apache Airflow", C.DATA_ENGINEERING, 1.3, ("airflow",)),
    ("Prefect", C.DATA_ENGINEERING, 1.0, ()),
    ("Dagster", C.DATA_ENGINEERING, 1.0, ()),
    ("dbt", C.DATA_ENGINEERING, 1.2, ("data build tool",)),
    ("Apache Flink", C.DATA_ENGINEERING, 1.1, ("flink",)),
    ("Apache Beam", C.DATA_ENGINEERING, 1.0, ()),
    ("Apache Hive", C.DATA_ENGINEERING, 0.8, ("hive",)),
    ("Presto", C.DATA_ENGINEERING, 0.9, ("trino",)),
    ("ETL", C.DATA_ENGINEERING, 1.2, ("elt", "etl pipelines", "data pipelines")),
    ("Data Warehousing", C.DATA_ENGINEERING, 1.2, ("data warehouse", "dimensional modeling", "star schema")),
    ("Data Lake", C.DATA_ENGINEERING, 1.1, ("lakehouse", "delta lake")),
    ("Data Governance", C.DATA_ENGINEERING, 1.1, ("data quality", "data lineage", "data catalog")),
    ("Stream Processing", C.DATA_ENGINEERING, 1.2, ("real-time processing", "streaming data")),
    ("Web Scraping", C.DATA_ENGINEERING, 0.9, ("beautifulsoup", "scrapy", "crawling")),
    ("Excel", C.TOOL, 0.7, ("microsoft excel", "ms excel", "advanced excel", "pivot tables")),
    ("Google Sheets", C.TOOL, 0.6, ()),
    ("A/B Testing", C.DATA_SCIENCE, 1.1, ("split testing", "experimentation")),
    ("SPSS", C.DATA_SCIENCE, 0.7, ()),
    ("SAS", C.DATA_SCIENCE, 0.8, ()),
    ("Stata", C.DATA_SCIENCE, 0.7, ()),
)

# ---------------------------------------------------------------------------
# Mobile
# ---------------------------------------------------------------------------

_MOBILE: Final[tuple[SkillSpec, ...]] = (
    ("React Native", C.MOBILE, 1.2, ("react-native",)),
    ("Flutter", C.MOBILE, 1.2, ()),
    ("Android Development", C.MOBILE, 1.1, ("android sdk", "android studio", "jetpack compose")),
    ("iOS Development", C.MOBILE, 1.1, ("ios sdk", "xcode", "uikit")),
    ("Ionic", C.MOBILE, 0.8, ()),
    ("Xamarin", C.MOBILE, 0.7, ()),
    ("Cordova", C.MOBILE, 0.6, ("phonegap",)),
    ("Expo", C.MOBILE, 0.9, ()),
    ("Mobile UI Design", C.MOBILE, 0.9, ("mobile ux",)),
    ("App Store Deployment", C.MOBILE, 0.9, ("play store", "app store connect", "testflight")),
    ("Push Notifications", C.MOBILE, 0.8, ("fcm", "apns")),
    ("Core Data", C.MOBILE, 0.8, ()),
    ("Room Database", C.MOBILE, 0.8, ()),
    ("Retrofit", C.MOBILE, 0.8, ()),
)

# ---------------------------------------------------------------------------
# Cybersecurity
# ---------------------------------------------------------------------------

_SECURITY: Final[tuple[SkillSpec, ...]] = (
    ("Cybersecurity", C.CYBERSECURITY, 1.3, ("cyber security", "information security", "infosec")),
    ("Penetration Testing", C.CYBERSECURITY, 1.3, ("pentesting", "pen testing", "ethical hacking")),
    ("Vulnerability Assessment", C.CYBERSECURITY, 1.2, ("vulnerability scanning", "vulnerability management")),
    ("Application Security", C.CYBERSECURITY, 1.3, ("appsec", "secure coding", "owasp")),
    ("Network Security", C.CYBERSECURITY, 1.2, ("firewall configuration", "ids", "ips")),
    ("Cryptography", C.CYBERSECURITY, 1.2, ("encryption", "pki", "tls", "ssl")),
    ("Identity and Access Management", C.CYBERSECURITY, 1.2, ("iam", "sso", "saml", "rbac")),
    ("Zero Trust", C.CYBERSECURITY, 1.2, ("zero trust architecture",)),
    ("SIEM", C.CYBERSECURITY, 1.2, ("security information and event management",)),
    ("Threat Modeling", C.CYBERSECURITY, 1.2, ("threat modelling", "threat analysis")),
    ("Incident Response", C.CYBERSECURITY, 1.2, ("digital forensics", "forensics")),
    ("Malware Analysis", C.CYBERSECURITY, 1.1, ("reverse engineering",)),
    ("Security Auditing", C.CYBERSECURITY, 1.1, ("security audit", "compliance audit")),
    ("DevSecOps", C.CYBERSECURITY, 1.3, ("dev sec ops", "security automation")),
    ("Metasploit", C.CYBERSECURITY, 1.0, ()),
    ("Burp Suite", C.CYBERSECURITY, 1.1, ("burpsuite",)),
    ("Nmap", C.CYBERSECURITY, 1.0, ()),
    ("Wireshark", C.CYBERSECURITY, 1.0, ()),
    ("Kali Linux", C.CYBERSECURITY, 1.0, ()),
    ("Nessus", C.CYBERSECURITY, 0.9, ()),
    ("Snyk", C.CYBERSECURITY, 1.0, ()),
    ("SonarQube", C.CYBERSECURITY, 1.0, ("sonar qube", "static analysis", "sast")),
    ("GDPR", C.CYBERSECURITY, 1.0, ("gdpr compliance", "data privacy")),
    ("SOC 2", C.CYBERSECURITY, 1.1, ("soc2",)),
    ("ISO 27001", C.CYBERSECURITY, 1.1, ("iso27001",)),
    ("HIPAA", C.CYBERSECURITY, 1.0, ("hipaa compliance",)),
    ("PCI DSS", C.CYBERSECURITY, 1.0, ("pci-dss",)),
    ("Risk Assessment", C.CYBERSECURITY, 1.1, ("risk management", "risk analysis")),
)

# ---------------------------------------------------------------------------
# Testing and quality
# ---------------------------------------------------------------------------

_TESTING: Final[tuple[SkillSpec, ...]] = (
    ("Unit Testing", C.TESTING, 1.0, ("unit tests", "unittest")),
    ("Integration Testing", C.TESTING, 1.0, ("integration tests",)),
    ("End-to-End Testing", C.TESTING, 1.1, ("e2e testing", "end to end testing")),
    ("Test Automation", C.TESTING, 1.2, ("automated testing", "automation testing")),
    ("Test-Driven Development", C.TESTING, 1.2, ("tdd", "bdd", "behavior-driven development")),
    ("pytest", C.TESTING, 1.0, ("py.test",)),
    ("unittest", C.TESTING, 0.8, ()),
    ("Jest", C.TESTING, 1.0, ()),
    ("Mocha", C.TESTING, 0.8, ("chai",)),
    ("Vitest", C.TESTING, 0.9, ()),
    ("JUnit", C.TESTING, 1.0, ()),
    ("TestNG", C.TESTING, 0.8, ()),
    ("Selenium", C.TESTING, 0.9, ("selenium webdriver",)),
    ("Cypress", C.TESTING, 1.1, ()),
    ("Playwright", C.TESTING, 1.2, ()),
    ("Puppeteer", C.TESTING, 0.9, ()),
    ("Appium", C.TESTING, 0.9, ()),
    ("Postman", C.TESTING, 0.9, ()),
    ("JMeter", C.TESTING, 0.9, ("apache jmeter",)),
    ("Locust", C.TESTING, 0.9, ()),
    ("k6", C.TESTING, 0.9, ()),
    ("Performance Testing", C.TESTING, 1.1, ("load testing", "stress testing")),
    ("Regression Testing", C.TESTING, 0.9, ()),
    ("Code Coverage", C.TESTING, 0.9, ("test coverage",)),
    ("Quality Assurance", C.TESTING, 1.0, ("qa", "qa engineering")),
    ("Mocking", C.TESTING, 0.9, ("mock objects", "stubbing")),
    ("Contract Testing", C.TESTING, 0.9, ("pact",)),
    ("Chaos Engineering", C.TESTING, 1.0, ("chaos testing",)),
)

# ---------------------------------------------------------------------------
# Operating systems, networking, version control, hardware
# ---------------------------------------------------------------------------

_SYSTEMS: Final[tuple[SkillSpec, ...]] = (
    ("Linux", C.OPERATING_SYSTEM, 1.1, ("ubuntu", "debian", "centos", "rhel", "red hat", "fedora")),
    ("Unix", C.OPERATING_SYSTEM, 0.9, ("solaris", "aix")),
    ("Windows Server", C.OPERATING_SYSTEM, 0.9, ("windows administration",)),
    ("macOS", C.OPERATING_SYSTEM, 0.7, ("mac os",)),
    ("Shell Scripting", C.OPERATING_SYSTEM, 1.0, ("shell scripts",)),
    ("System Administration", C.OPERATING_SYSTEM, 1.0, ("sysadmin", "systems administration")),
    ("Embedded Systems", C.OPERATING_SYSTEM, 1.1, ("rtos", "firmware")),
    ("Virtualization", C.OPERATING_SYSTEM, 1.0, ("vmware", "virtualbox", "hyper-v", "kvm")),
    ("Git", C.VERSION_CONTROL, 1.1, ("git flow", "gitflow")),
    ("GitHub", C.VERSION_CONTROL, 1.0, ()),
    ("GitLab", C.VERSION_CONTROL, 1.0, ()),
    ("Bitbucket", C.VERSION_CONTROL, 0.9, ()),
    ("Subversion", C.VERSION_CONTROL, 0.6, ("svn",)),
    ("Mercurial", C.VERSION_CONTROL, 0.5, ()),
    ("Code Review", C.VERSION_CONTROL, 1.1, ("peer review", "pull requests", "merge requests")),
    ("Branching Strategy", C.VERSION_CONTROL, 0.9, ("trunk-based development", "monorepo")),
    ("TCP/IP", C.NETWORKING, 1.0, ("tcp ip", "networking protocols")),
    ("DNS", C.NETWORKING, 0.9, ("domain name system",)),
    ("HTTP/HTTPS", C.NETWORKING, 0.9, ("http", "https", "http/2")),
    ("VPN", C.NETWORKING, 0.9, ("virtual private network",)),
    ("Network Administration", C.NETWORKING, 1.0, ("network engineering",)),
    ("Routing and Switching", C.NETWORKING, 1.0, ("bgp", "ospf", "vlan")),
    ("Cisco", C.NETWORKING, 0.9, ("cisco ios",)),
    ("Firewalls", C.NETWORKING, 1.0, ("iptables", "pfsense")),
    ("Proxy Servers", C.NETWORKING, 0.8, ("reverse proxy", "haproxy")),
    ("Network Troubleshooting", C.NETWORKING, 0.9, ("packet analysis",)),
    ("SNMP", C.NETWORKING, 0.7, ()),
    ("SD-WAN", C.NETWORKING, 0.9, ()),
)

# ---------------------------------------------------------------------------
# Tools, methodologies, design, soft skills
# ---------------------------------------------------------------------------

_TOOLS: Final[tuple[SkillSpec, ...]] = (
    ("Jira", C.TOOL, 0.8, ("atlassian jira",)),
    ("Confluence", C.TOOL, 0.7, ()),
    ("Trello", C.TOOL, 0.6, ()),
    ("Asana", C.TOOL, 0.6, ()),
    ("Linear", C.TOOL, 0.7, ()),
    ("Notion", C.TOOL, 0.7, ()),
    ("Slack", C.TOOL, 0.6, ()),
    ("Figma", C.TOOL, 1.0, ()),
    ("Adobe XD", C.TOOL, 0.8, ()),
    ("Sketch", C.TOOL, 0.7, ()),
    ("Adobe Photoshop", C.TOOL, 0.6, ("photoshop",)),
    ("Adobe Illustrator", C.TOOL, 0.6, ("illustrator",)),
    ("Canva", C.TOOL, 0.5, ()),
    ("VS Code", C.TOOL, 0.7, ("visual studio code",)),
    ("IntelliJ IDEA", C.TOOL, 0.7, ("intellij",)),
    ("PyCharm", C.TOOL, 0.7, ()),
    ("Vim", C.TOOL, 0.7, ("neovim",)),
    ("Agile", C.TOOL, 0.9, ("agile methodology", "agile methodologies")),
    ("Scrum", C.TOOL, 0.9, ("scrum master", "sprint planning")),
    ("Kanban", C.TOOL, 0.8, ()),
    ("SAFe", C.TOOL, 0.8, ("scaled agile framework",)),
    ("Waterfall", C.TOOL, 0.5, ()),
    ("Project Management", C.TOOL, 1.0, ("program management", "delivery management")),
    ("Product Management", C.TOOL, 1.1, ("product ownership", "product owner", "roadmapping")),
    ("Stakeholder Management", C.SOFT_SKILL, 1.0, ("stakeholder engagement",)),
    ("Technical Writing", C.SOFT_SKILL, 1.0, ("documentation", "technical documentation")),
    ("UI/UX Design", C.TOOL, 1.1, ("ux design", "ui design", "user experience", "user interface design")),
    ("Design Systems", C.TOOL, 1.0, ("component library",)),
    ("Wireframing", C.TOOL, 0.8, ("prototyping", "mockups")),
    ("User Research", C.TOOL, 1.0, ("usability testing",)),
    ("SEO", C.TOOL, 0.8, ("search engine optimization",)),
    ("Salesforce", C.TOOL, 1.0, ("salesforce crm", "apex")),
    ("SAP", C.TOOL, 1.0, ("sap erp",)),
    ("ServiceNow", C.TOOL, 1.0, ()),
    ("Zapier", C.TOOL, 0.6, ()),
    ("Leadership", C.SOFT_SKILL, 1.1, ("team leadership", "tech lead", "people management")),
    ("Mentoring", C.SOFT_SKILL, 1.0, ("coaching", "mentorship")),
    ("Communication", C.SOFT_SKILL, 1.0, ("verbal communication", "written communication")),
    ("Problem Solving", C.SOFT_SKILL, 1.0, ("analytical thinking", "critical thinking")),
    ("Collaboration", C.SOFT_SKILL, 0.9, ("teamwork", "cross-functional collaboration")),
    ("Time Management", C.SOFT_SKILL, 0.8, ("prioritization",)),
    ("Adaptability", C.SOFT_SKILL, 0.8, ("flexibility",)),
    ("Presentation Skills", C.SOFT_SKILL, 0.9, ("public speaking",)),
    ("Negotiation", C.SOFT_SKILL, 0.9, ()),
    ("Customer Focus", C.SOFT_SKILL, 0.9, ("client management", "customer success")),
    ("Design Patterns", C.FRAMEWORK, 1.2, ("gof patterns", "solid principles")),
    ("Object-Oriented Programming", C.FRAMEWORK, 1.1, ("oop", "object oriented programming")),
    ("Functional Programming", C.FRAMEWORK, 1.1, ("fp",)),
    ("Data Structures", C.FRAMEWORK, 1.2, ("data structures and algorithms", "dsa")),
    ("Algorithms", C.FRAMEWORK, 1.2, ("algorithm design", "complexity analysis")),
    ("Refactoring", C.FRAMEWORK, 1.0, ("code refactoring", "technical debt")),
    ("Clean Code", C.FRAMEWORK, 1.0, ("clean architecture",)),
    ("Pair Programming", C.FRAMEWORK, 0.8, ()),
    ("Blockchain", C.FRAMEWORK, 1.0, ("web3", "smart contracts", "ethereum")),
    ("Internet of Things", C.FRAMEWORK, 1.0, ("iot", "mqtt")),
    ("Game Development", C.FRAMEWORK, 0.9, ("unity", "unreal engine", "godot")),
    ("AR/VR", C.FRAMEWORK, 1.0, ("augmented reality", "virtual reality", "xr")),
    ("Quantum Computing", C.FRAMEWORK, 0.9, ("qiskit",)),
)

# ---------------------------------------------------------------------------
# Additional specialised and emerging technologies
# ---------------------------------------------------------------------------

_SPECIALISED: Final[tuple[SkillSpec, ...]] = (
    ("Apache Superset", C.DATA_SCIENCE, 0.9, ("superset",)),
    ("Great Expectations", C.DATA_ENGINEERING, 0.9, ("data validation",)),
    ("Apache NiFi", C.DATA_ENGINEERING, 0.8, ("nifi",)),
    ("Talend", C.DATA_ENGINEERING, 0.8, ()),
    ("Informatica", C.DATA_ENGINEERING, 0.8, ()),
    ("SSIS", C.DATA_ENGINEERING, 0.8, ("sql server integration services",)),
    ("Fivetran", C.DATA_ENGINEERING, 0.9, ()),
    ("Debezium", C.DATA_ENGINEERING, 0.9, ("change data capture", "cdc")),
    ("Iceberg", C.DATA_ENGINEERING, 1.0, ("apache iceberg", "apache hudi")),
    ("Feature Store", C.MACHINE_LEARNING, 1.1, ("feast",)),
    ("Model Monitoring", C.MACHINE_LEARNING, 1.2, ("model drift", "data drift")),
    ("AutoML", C.MACHINE_LEARNING, 1.0, ("automated machine learning",)),
    ("Bayesian Statistics", C.DATA_SCIENCE, 1.0, ("bayesian inference",)),
    ("Causal Inference", C.DATA_SCIENCE, 1.1, ("causal analysis",)),
    ("Optimization", C.DATA_SCIENCE, 1.0, ("linear programming", "operations research")),
    ("Graph Neural Networks", C.DEEP_LEARNING, 1.1, ("gnn",)),
    ("Generative Adversarial Networks", C.DEEP_LEARNING, 1.0, ("gan", "gans")),
    ("Convolutional Neural Networks", C.DEEP_LEARNING, 1.1, ("cnn", "cnns")),
    ("Recurrent Neural Networks", C.DEEP_LEARNING, 1.0, ("rnn", "lstm", "gru")),
    ("Attention Mechanisms", C.DEEP_LEARNING, 1.1, ("self-attention",)),
    ("Transfer Learning", C.DEEP_LEARNING, 1.1, ()),
    ("Knowledge Graphs", C.AI, 1.1, ("ontology", "sparql")),
    ("Agentic AI", C.AI, 1.3, ("ai agents", "autonomous agents", "multi-agent")),
    ("Model Context Protocol", C.AI, 1.1, ("mcp",)),
    ("Guardrails", C.AI, 1.1, ("ai safety", "content moderation")),
    ("Ollama", C.AI, 1.0, ()),
    ("vLLM", C.AI, 1.1, ()),
    ("Triton Inference Server", C.AI, 1.0, ("triton",)),
    ("ONNX", C.AI, 1.0, ("onnx runtime",)),
    ("CUDA", C.AI, 1.2, ("gpu programming", "nvidia cuda")),
    ("Distributed Training", C.DEEP_LEARNING, 1.2, ("data parallelism", "deepspeed")),
    ("Quantization", C.AI, 1.1, ("model quantization", "model compression")),
    ("gRPC Streaming", C.BACKEND, 0.9, ("bidirectional streaming",)),
    ("Server-Sent Events", C.BACKEND, 0.8, ("sse",)),
    ("Idempotency", C.BACKEND, 0.9, ("exactly-once", "idempotent")),
    ("CQRS", C.BACKEND, 1.0, ("command query responsibility segregation",)),
    ("Saga Pattern", C.BACKEND, 1.0, ("distributed transactions",)),
    ("Circuit Breaker", C.BACKEND, 0.9, ("resilience patterns", "retry logic")),
    ("Feature Flags", C.DEVOPS, 0.9, ("launchdarkly", "feature toggles")),
    ("Backstage", C.DEVOPS, 0.9, ("developer portal", "platform engineering")),
    ("Crossplane", C.DEVOPS, 0.9, ()),
    ("Karpenter", C.DEVOPS, 0.9, ("cluster autoscaler",)),
    ("Falco", C.CYBERSECURITY, 0.9, ("runtime security",)),
    ("Trivy", C.CYBERSECURITY, 0.9, ("container scanning",)),
    ("Dependabot", C.CYBERSECURITY, 0.8, ("dependency scanning", "sca")),
    ("Secrets Rotation", C.CYBERSECURITY, 0.9, ("key management", "kms")),
    ("Bug Bounty", C.CYBERSECURITY, 0.9, ("responsible disclosure",)),
    ("Red Teaming", C.CYBERSECURITY, 1.1, ("blue team", "purple team")),
    ("Active Directory", C.NETWORKING, 0.9, ("ldap", "azure ad", "entra id")),
    ("Load Testing Strategy", C.TESTING, 0.9, ("soak testing", "spike testing")),
    ("Visual Regression Testing", C.TESTING, 0.9, ("snapshot testing", "percy")),
    ("Accessibility Testing", C.TESTING, 1.0, ("axe", "screen reader testing")),
    ("Property-Based Testing", C.TESTING, 0.9, ("hypothesis testing framework", "fuzzing")),
    ("Robot Framework", C.TESTING, 0.7, ()),
    ("Cucumber", C.TESTING, 0.8, ("gherkin",)),
    ("Detox", C.TESTING, 0.7, ()),
    ("Compose Multiplatform", C.MOBILE, 0.9, ("kotlin multiplatform", "kmm")),
    ("Mobile Performance", C.MOBILE, 0.9, ("app optimization", "startup time")),
    ("Deep Linking", C.MOBILE, 0.8, ("universal links",)),
    ("In-App Purchases", C.MOBILE, 0.8, ("iap", "subscription billing")),
    ("Stripe API", C.BACKEND, 1.0, ("stripe integration", "payment processing")),
    ("Twilio", C.BACKEND, 0.8, ()),
    ("SendGrid", C.BACKEND, 0.7, ()),
    ("Auth0", C.BACKEND, 1.0, ("okta", "clerk")),
    ("Elastic Load Balancer", C.CLOUD, 1.0, ("elb", "alb")),
    ("Amazon SQS", C.CLOUD, 1.0, ("sqs", "sns")),
    ("Amazon Aurora", C.CLOUD, 1.1, ("aurora",)),
    ("Azure Blob Storage", C.CLOUD, 1.0, ("blob storage",)),
    ("Google Cloud Storage", C.CLOUD, 1.0, ("gcs",)),
    ("Cloud Run", C.CLOUD, 1.1, ("google cloud run",)),
    ("Firebase Auth", C.CLOUD, 0.9, ()),
    ("WebAssembly", C.FRONTEND, 1.0, ("wasm",)),
    ("Micro Frontends", C.FRONTEND, 1.0, ("module federation",)),
    ("Server-Side Rendering", C.FRONTEND, 1.1, ("ssr", "static site generation", "ssg")),
    ("Core Web Vitals", C.FRONTEND, 1.0, ("lighthouse", "web performance")),
    ("Internationalization", C.FRONTEND, 0.9, ("i18n", "localization", "l10n")),
    ("Animation", C.FRONTEND, 0.8, ("framer motion", "gsap")),
    ("Data Structures Optimization", C.FRAMEWORK, 1.0, ("memory optimization", "profiling")),
    ("Compiler Design", C.FRAMEWORK, 1.0, ("parsing", "interpreters")),
    ("Distributed Consensus", C.FRAMEWORK, 1.1, ("raft", "paxos")),
    ("Technical Interviewing", C.SOFT_SKILL, 0.9, ("hiring", "interview panel")),
    ("Cross-Functional Leadership", C.SOFT_SKILL, 1.1, ("matrix management",)),
    ("Conflict Resolution", C.SOFT_SKILL, 0.9, ()),
    ("Strategic Planning", C.SOFT_SKILL, 1.0, ("okrs", "goal setting")),
    ("Data Storytelling", C.SOFT_SKILL, 1.0, ("executive communication",)),
    ("Budget Management", C.SOFT_SKILL, 0.9, ("resource planning",)),
    ("Vendor Management", C.SOFT_SKILL, 0.9, ("procurement",)),
    ("Change Management", C.SOFT_SKILL, 0.9, ("organizational change",)),
    ("Remote Collaboration", C.SOFT_SKILL, 0.8, ("distributed teams", "async communication")),
    ("Open Source Contribution", C.VERSION_CONTROL, 1.0, ("oss contributor", "maintainer")),
    ("Semantic Versioning", C.VERSION_CONTROL, 0.8, ("semver", "release management")),
    ("Monorepo Tooling", C.VERSION_CONTROL, 0.9, ("nx", "turborepo", "bazel")),
    ("Makefile", C.TOOL, 0.7, ("make", "build automation")),
    ("Gradle", C.TOOL, 0.9, ()),
    ("Maven", C.TOOL, 0.9, ("apache maven",)),
    ("npm", C.TOOL, 0.8, ("yarn", "pnpm")),
    ("Poetry", C.TOOL, 0.8, ("pipenv", "uv")),
    ("Conda", C.TOOL, 0.8, ("anaconda", "miniconda")),
    ("Ruff", C.TOOL, 0.8, ("black formatter", "flake8")),
    ("mypy", C.TOOL, 0.9, ("type checking", "static typing")),
    ("Pre-commit", C.TOOL, 0.8, ("pre-commit hooks", "git hooks")),
    ("Swagger UI", C.TOOL, 0.8, ("api documentation",)),
    ("Miro", C.TOOL, 0.6, ("figjam", "whiteboarding")),
    ("Amplitude", C.TOOL, 0.8, ("mixpanel", "product analytics")),
    ("Segment", C.TOOL, 0.8, ("event tracking",)),
    ("HubSpot", C.TOOL, 0.7, ()),
    ("Zendesk", C.TOOL, 0.6, ()),
    ("Shopify", C.TOOL, 0.8, ("shopify plus",)),
    ("WordPress", C.TOOL, 0.6, ("wordpress development",)),
    ("Contentful", C.TOOL, 0.8, ("headless cms", "strapi", "sanity")),
)

#: The complete catalog, assembled from every category group.
SKILL_CATALOG: Final[tuple[SkillSpec, ...]] = (
    *_PROGRAMMING,
    *_FRONTEND,
    *_BACKEND,
    *_DATABASES,
    *_CLOUD,
    *_DEVOPS,
    *_AI_ML,
    *_DATA,
    *_MOBILE,
    *_SECURITY,
    *_TESTING,
    *_SYSTEMS,
    *_TOOLS,
    *_SPECIALISED,
)
